// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/ptflp/geotask/module/courierfacade/models"
)

// CourierFacer is an autogenerated mock type for the CourierFacer type
type CourierFacer struct {
	mock.Mock
}

// GetStatus provides a mock function with given fields: ctx
func (_m *CourierFacer) GetStatus(ctx context.Context) models.CourierStatus {
	ret := _m.Called(ctx)

	var r0 models.CourierStatus
	if rf, ok := ret.Get(0).(func(context.Context) models.CourierStatus); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.CourierStatus)
	}

	return r0
}

// MoveCourier provides a mock function with given fields: ctx, direction, zoom
func (_m *CourierFacer) MoveCourier(ctx context.Context, direction int, zoom int) {
	_m.Called(ctx, direction, zoom)
}

type mockConstructorTestingTNewCourierFacer interface {
	mock.TestingT
	Cleanup(func())
}

// NewCourierFacer creates a new instance of CourierFacer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCourierFacer(t mockConstructorTestingTNewCourierFacer) *CourierFacer {
	mock := &CourierFacer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
